version: "3.8"

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--api.insecure=true"  # Включает API и dashboard для мониторинга
      - "--providers.docker=true"  # Включает интеграцию с Docker
      - "--entrypoints.web.address=:80"  # Порт для HTTP
    ports:
      - "8080:8080"  
      - "80:80"      
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Для доступа к Docker API

  web1:
    image: nginx:1.26.0
    container_name: web1_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"  #говорит Traefik, что он должен направлять все HTTP-запросы, пришедшие на хост localhost, на контейнер web1.
      - "traefik.http.services.web.loadbalancer.server.port=80"  # Порт, на котором работает веб-сервер

    volumes:
      - ./html/web1:/usr/share/nginx/html:ro  # Монтирование HTML файлов

  web2:
    image: nginx:1.26.0
    container_name: web2_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"  # То же правило для маршрутизации на localhost
      - "traefik.http.services.web.loadbalancer.server.port=80"  # Порт, на котором работает веб-сервер

    volumes:
      - ./html/web2:/usr/share/nginx/html:ro  # Монтирование HTML файлов
