all:
  hosts:
    container1:
      ansible_host: localhost
      ansible_port: 2222
      ansible_user: ansible_user
      #ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_ssh_pass: qwerty
      ansible_python_interpreter: /usr/bin/python3
    container2:
      ansible_host: localhost
      ansible_port: 2223
      ansible_user: ansible_user
      #ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_ssh_pass: qwerty
      ansible_python_interpreter: /usr/bin/python3