version: "2.30.3"

services:
  balancer:
    image: nginx:1.26.0
    container_name: balancer
    ports:
      - 80:80
    volumes:
      - ./balancer.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web1
      - web2

  web1:
    image: nginx:1.26.0
    container_name: web1
    volumes:
      - ./html/web1:/usr/share/nginx/html:ro

  web2:
    image: nginx:1.26.0
    container_name: web2
    volumes:
      - ./html/web2:/usr/share/nginx/html:ro
